# Default values for tiflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# clusterName: demo

image:
  repository: dataflow
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: test

master:
  replicas: 3
  dataStorage: 2Gi
  logStorage: 1Gi
  config: |
    [framework-meta]
    user = "root"
    password = ""
    schema = "test_framework"

    [business-meta]
    user = "root"
    password = ""
    schema = "test_business"
  resources: 
    requests:
      cpu: 2000m
      memory: 4Gi

executor:
  replicas: 4
  logStorage: 1Gi
  config: |
    keepalive-ttl = "20s"
    keepalive-interval = "500ms"
    session-ttl = 20
  resources: 
    requests:
      cpu: 2000m
      memory: 4Gi

metastore:
  frameworkStorage: 5Gi
  businessStorage: 5Gi

cases:
  enabled: false
  repository: dataflow
  tag: test

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
